Repository rsalmei/alive-progress, pull requests merged in 2022-02, with the labels that each got.

#131 2.2.0
  CHANGELOG.md
  README.md
  alive_progress/__init__.py
  alive_progress/core/calibration.py
  alive_progress/core/configuration.py
  alive_progress/core/hook_manager.py
  alive_progress/core/progress.py
  alive_progress/utils/cells.py
  alive_progress/utils/terminal/__init__.py
  alive_progress/utils/terminal/jupyter.py
  alive_progress/utils/terminal/non_tty.py
  alive_progress/utils/terminal/tty.py
  alive_progress/utils/terminal/void.py
  noxfile.py
  requirements/test.txt
  setup.py
  tests/animations/test_spinners.py
  tests/conftest.py
  tests/core/test_calibration.py
  tests/core/test_hook_manager.py
  tests/core/test_progress.py
  tests/utils/test_cells.py
Labels: size/XL

#136 Customizable widgets!
  CHANGELOG.md
  README.md
  alive_progress/__init__.py
  alive_progress/animations/bars.py
  alive_progress/core/configuration.py
  alive_progress/core/progress.py
  tests/core/test_configuration.py
Labels: size/L

#137 2.3.1
  CHANGELOG.md
  README.md
  alive_progress/__init__.py
  alive_progress/core/configuration.py
  alive_progress/core/progress.py
  alive_progress/styles/internal.py
  alive_progress/utils/colors.py
  alive_progress/utils/terminal/__init__.py
  alive_progress/utils/terminal/tty.py
  alive_progress/utils/terminal/void.py
Labels: size/L

#108 Add 'circles' and 'squares' spinners
  alive_progress/styles/internal.py
Labels: size/XS

#80 a few minor changes.
  setup.py
Labels: size/XS
